server:
  port: 8080


spring:
  datasource:
    username: root
    password: gsq123
    url: jdbc:mysql://localhost:3306/bishe?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/qingda/lr/mapper/*.xml
  type-aliases-package: com.qingda.lr.entity




#showSql
logging:
  level:
    org:
      lanqiao:
        myjd :
          mapper: debug

